### ISSUE TITLE
getting module not found 

### ISSUE THREAD

**Issue by thakuradi** [alejandro-ao/langchain-ask-pdf#10]
even i installed the module it's showing me not found
 streamlit run app.py
Traceback (most recent call last):
  File "/home/thakuradi/.local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.runtime.app_session import AppSession
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/runtime/app_session.py", line 35, in <module>
    from streamlit.runtime import caching, legacy_caching
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/runtime/caching/__init__.py", line 21, in <module>
    from streamlit.runtime.caching.cache_data_api import (
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 37, in <module>
    from streamlit.runtime.caching import cache_utils
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 31, in <module>
    from streamlit import type_util
  File "/home/thakuradi/.local/lib/python3.11/site-packages/streamlit/type_util.py", line 42, in <module>
    from pandas import DataFrame, Index, MultiIndex, Series
  File "/home/thakuradi/.local/lib/python3.11/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakuradi/.local/lib/python3.11/site-packages/pandas/compat/__init__.py", line 24, in <module>
    import pandas.compat.compressors
  File "/home/thakuradi/.local/lib/python3.11/site-packages/pandas/compat/compressors.py", line 7, in <module>
    import bz2
  File "/usr/local/lib/python3.11/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

**Comment by thakuradi** [comment]
i tried unistalling and installin the module but it's still showing

**Comment by axsddlr** [comment]
> i tried unistalling and installin the module but it's still showing

dont use python 3.11. Use python 3.10.x. 3.11 is not supported by every library yet

**Comment by bbaaxx** [comment]
I think you may be missing libbz2-dev:

`sudo apt-get install libbz2-dev` 

https://stackoverflow.com/questions/12806122/missing-python-bz2-module

**Comment by axsddlr** [comment]
> I think you may be missing libbz2-dev:
> 
> `sudo apt-get install libbz2-dev`
> 
> https://stackoverflow.com/questions/12806122/missing-python-bz2-module

too bad im running this on windows

**Comment by bbaaxx** [comment]
@axsddlr I am not a windows user, but have you tried this?

https://gnuwin32.sourceforge.net/packages/bzip2.htm
